### ISSUE TITLE
Get Started button​

### ISSUE THREAD

**Issue by castilloedwin** [WasperAI/Wasper#1]
### What happened?

Hey team I noticed the Get Started button at the end of the home page is broken

### Distribution version

Web (app.Wasper.app)

### What browsers are you seeing the problem on if you're using web version?

Chrome, Other

### Are you self-hosting?

- [ ] Yes

**Comment by danielchim** [comment]
That's because the whole thing is stolen from toeverything/affine

Make a issue right there.
